# Site settings
title:          HasieraOne
description:    "I will greet this day with love in my heart."
baseurl:
url:            "https://hasieraone.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         njar
  url:
  email:        hasieraone@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
